//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MergeHelper {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Preferences : global::System.Configuration.ApplicationSettingsBase {
        
        private static Preferences defaultInstance = ((Preferences)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Preferences())));
        
        public static Preferences Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\WS\\TH_HSP150001_All\\src\\HM\\Xdd\\mddp_HSP_V15_1_0238_002_Softstarter_3RW5_V15.1." +
            "0.0.xml")]
        public string PACKAGE_PATH {
            get {
                return ((string)(this["PACKAGE_PATH"]));
            }
            set {
                this["PACKAGE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\WS\\WM5_WinCC_HW_Work")]
        public string WM5_PATH {
            get {
                return ((string)(this["WM5_PATH"]));
            }
            set {
                this["WM5_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CHANGESET_START {
            get {
                return ((int)(this["CHANGESET_START"]));
            }
            set {
                this["CHANGESET_START"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HSP_XDD_PATH {
            get {
                return ((string)(this["HSP_XDD_PATH"]));
            }
            set {
                this["HSP_XDD_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("src\\HWCN\\XDDINTT\\MddConverter2Mdd3\\Siemens.Simatic.Hwcn.Interpreter.mdddllconvert" +
            "er.exe")]
        public string MDD_CONVERTER_EXE {
            get {
                return ((string)(this["MDD_CONVERTER_EXE"]));
            }
            set {
                this["MDD_CONVERTER_EXE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MDD_CONVERTER_FOLDER {
            get {
                return ((string)(this["MDD_CONVERTER_FOLDER"]));
            }
            set {
                this["MDD_CONVERTER_FOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string COMPARISON_SOURCE_FOLDER {
            get {
                return ((string)(this["COMPARISON_SOURCE_FOLDER"]));
            }
            set {
                this["COMPARISON_SOURCE_FOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("src\\HM\\Xdd3")]
        public string COMPARISON_TARGET_FOLDER {
            get {
                return ((string)(this["COMPARISON_TARGET_FOLDER"]));
            }
            set {
                this["COMPARISON_TARGET_FOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mddp_HSP_V15_1_0238_002_Softstarter_3RW5_V15.1.0.0.xml")]
        public string PACKAGE_NAME {
            get {
                return ((string)(this["PACKAGE_NAME"]));
            }
            set {
                this["PACKAGE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CHANGESET_END {
            get {
                return ((int)(this["CHANGESET_END"]));
            }
            set {
                this["CHANGESET_END"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HSP_XDDSHPASS1_PATH {
            get {
                return ((string)(this["HSP_XDDSHPASS1_PATH"]));
            }
            set {
                this["HSP_XDDSHPASS1_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\WS\\TH_HSP150001_All")]
        public string HSP_PATH {
            get {
                return ((string)(this["HSP_PATH"]));
            }
            set {
                this["HSP_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("languages\\Simatic\\Common\\Tooltips")]
        public string HSP_TOOLTIPS_OTHER {
            get {
                return ((string)(this["HSP_TOOLTIPS_OTHER"]));
            }
            set {
                this["HSP_TOOLTIPS_OTHER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("src\\Simatic\\Common\\Tooltips\\en-US")]
        public string HSP_TOOLTIPS_ENGLISH {
            get {
                return ((string)(this["HSP_TOOLTIPS_ENGLISH"]));
            }
            set {
                this["HSP_TOOLTIPS_ENGLISH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CTHWCSOSTES3RW5*.zip")]
        public string TOOLTIP_FILE_PATTERN {
            get {
                return ((string)(this["TOOLTIP_FILE_PATTERN"]));
            }
            set {
                this["TOOLTIP_FILE_PATTERN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("languages\\Simatic\\Common\\Tooltips")]
        public string WM5_TOOLTIPS_OTHER {
            get {
                return ((string)(this["WM5_TOOLTIPS_OTHER"]));
            }
            set {
                this["WM5_TOOLTIPS_OTHER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("src\\Simatic\\Common\\Tooltips\\en-US")]
        public string WM5_TOOLTIPS_ENGLISH {
            get {
                return ((string)(this["WM5_TOOLTIPS_ENGLISH"]));
            }
            set {
                this["WM5_TOOLTIPS_ENGLISH"] = value;
            }
        }
    }
}
